services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - legacy

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  legacy:
    build:
      context: ./legacy
    ports:
      - "8082:80"
    volumes:
      - ./legacy:/usr/share/nginx/html:ro
